version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    # volumes:  # optional
    #   - /usr/src/app/downloads:/usr/src/app/downloads:rw 
    ports:
      - "80:80" # qbittorrent selection webserver
      - "8080:8080" # rclone serve index webserver
    restart: on-failure
      
      
